### ISSUE TITLE
[feat] 블로그 가입 페이지 및 계정&비밀번호 찾기

### ISSUE THREAD

**Issue by jiohjung98** [official-Trippy/trippy-front#12]
## Description
- 블로그 가입 페이지(1,2,3)단계를 구현할 예정입니다.
- 계정 및 비밀번호 찾기 페이지를 구현할 예정입니다.
- 로그인 되어있으면 로그인, 회원가입 페이지 접근을 이미 로그인되어있다는 알랄트와 함께 홈페이지 접근으로 리다이렉트할 예정입니다.
- 가입 완료 후 로그아웃 기능을 구현할 예정입니다.
- 닉네임 기입 시, 비속어 금지 처리를 할 예정입니다.
- 헤더에 검색창을 넣을 예정입니다.
- 유저 정보를 전역으로 관리할 예정입니다.
- 회원가입 완료 시, 뒤로가기 버튼 클릭 시 로직 생각

## Todo
- [x] 블로그 가입 페이지
- [x] 계정 찾기
- [x] 비밀번호 찾기
- [ ] 로그인 여부에 따른 로직 처리
- [ ] 로그아웃
- [ ] 닉네임 비속어 금지 처리
- [ ] 헤더 검색창
- [ ] 유저 정보 전역 관리
