### ISSUE TITLE
[feat] 인증인가 관련 추가 로직&프로필 모달

### ISSUE THREAD

**Issue by jiohjung98** [official-Trippy/trippy-front#14]
## Description
- 로그인 여부에 따른 로직 처리를 할 예정입니다.
- 가입 완료 후 로그아웃 기능을 구현할 예정입니다.
- 닉네임 기입 시, 비속어 금지 처리를 할 예정입니다.
- 헤더에 검색창을 넣을 예정입니다.
- 회원가입 완료 후, 뒤로가기 버튼 클릭 시 로직 구현할 예정입니다.
- 로그인 후 프로필 클릭 시, 모달 구현 예정입니다.
- 서비스 이용약관, 개인정보 처리 방침 페이지 구현 예정입니다.
- 벡엔드 api가 나옴에 따라 블로그 이미지 처리를 할 예정입니다.

## Todo
- [x] 로그인 후 로그인 페이지 접속 시 home으로 리다이렉트(임시 해결)
- [x] 로그아웃 기능
- [x] 닉네임 비속어 금지 처리
- [ ] 헤더 검색창
- [ ] 회원가입 후 로직 처리
- [x] 프로필 모달
- [ ] 서비스 이용약관, 개인정보 처리 방침 페이지
- [ ] 블로그 이미지 등록
