### ISSUE TITLE
[feat] 마이페이지 및 헤더 작업

### ISSUE THREAD

**Issue by jiohjung98** [official-Trippy/trippy-front#19]
## Description
- 헤더에 검색창을 넣을 예정입니다.
- 회원가입 완료 후, 뒤로가기 버튼 클릭 시 로직 구현할 예정입니다.
- 마이페이지 작업을 할 예정입니다.
- 회원탈퇴 기능을 추가할 예정입니다.
- 서비스 이용약관, 개인정보 처리 방침 페이지 구현 예정입니다.
- 벡엔드 api가 나옴에 따라 블로그 이미지 등록 처리를 할 예정입니다.

## Todo
- [x] 회원가입 후 로직
- [ ] 마이페이지 작업
- [ ] 회원탈퇴 작업
- [ ] 헤더 검색창 삽입 작업
- [ ] 서비스 이용약관, 개인정보 처리 방침 페이지
- [x] 블로그 이미지 등록
