### ISSUE TITLE
[feat] ootd & 내정보 수정 api

### ISSUE THREAD

**Issue by jiohjung98** [official-Trippy/trippy-front#45]
## Description
- ootd api 연동할 예정입니다.
- 내정보 수정 api 연동할 예정입니다.
- 회원탈퇴 api 예정입니다.
- 사진 용량 제한 걸릴 시, 텍스트 추가할 예정입니다.
- 게시글 api 연동되면 헤더에 검색창을 적용할 예정입니다.
- 카카오 및 구글 로고 받은 후에 모달에 적용할 예정입니다.
- 계정찾기 숫자 허용

## Todo
- [x] ootd api
- [ ] 내정보 수정 api
- [ ] 회원탈퇴 api
- [ ] 사진 용량 텍스트 처리
- [ ] 헤더 검색창
- [ ] 소셜로그인 이미지 적용
- [ ] 계정찾기 숫자 허용
