### ISSUE TITLE
[feat] 블로그 설정 및 마이페이지 구현

### ISSUE THREAD

**Issue by jiohjung98** [official-Trippy/trippy-front#5]
## Description
- 디자인이 나옴에 따라 블로그 설정 페이지 및 마이페이지를 구현할 예정입니다.
- 회원가입 페이지 디자인에 나옴에 따라 회원가입 레이아웃을 수정할 예정입니다.
- 헤더 레이아웃을 다시 잡을 예정입니다.
- 로그인 되어있으면 로그인, 회원가입 페이지 접근을 이미 로그인되어있다는 알랄트와 함께 홈페이지 접근으로 리다이렉트할 예정입니다.
- 컴포넌트 파일 내에 사용할 컴포넌트 기능들을 넣어두고 앱라우터에서는 해당 컴포넌트만 불러서 사용함으로써 가독성을 높일 예정입니다.

## Todo
- [x] 회원가입 페이지 레이아웃
- [x] 파일 분리
- [x] 헤더 높이 80px
- [x] width, height rem 변경
- [ ] 블로그 설정 페이지
- [ ] 마이페이지
- [ ] 토큰 관리 및 헤더 로딩 레이아웃
- [ ] 헤더 검색창 추가
- [ ] 로그인 후 로그인 및 회원가입 페이지 접근 x
- [ ] 로그아웃
- [ ] 닉네임 비속어 금지 처리
- [ ] Input박스 border 값 1px -> 0.5px
- [x] 로그인 페이지에만 헤더 제거
- [ ] 로그인 페이지 rem 작업 및 소셜 로그인 버튼 재디자인
