### ISSUE TITLE
feat: ootd&내정보 수정 api&회원 탈퇴 api

### ISSUE THREAD

**Issue by jiohjung98** [official-Trippy/trippy-front#58]
## Description
- ootd 렌더링 페이지 디자인 작업이 완료되면 디자인할 예정입니다.
- ootd 좋아요, 댓글, 수정, 삭제 등의 기능을 구현할 예정입니다.
- ootd 정렬 방식 벡엔드 api가 변경되면 적용할 예정입니다.
- ootd 관련 기능이 끝나면, 내정보 수정 api를 연동할 예정입니다.
- ootd 관련 기능이 끝나면, 헤더에 검색창을 넣어 검색 기능을 추가할 예정입니다.
- 회원탈퇴 api가 완료되면 연동할 예정입니다.
- 소셜로그인별 이미지 적용할 예정입니다.
- 계정찾기 숫자를 허용할 예정입니다.
- 사진 업로드 용량 초과 시, 텍스트 추가할 예정입니다.

## Todo
- [ ] ootd 각 페이지별 디자인 작업
- [ ] ootd 추가 기능
- [ ] ootd 정렬 기능
- [ ] 내정보 수정 api
- [ ] 헤더 검색창
- [ ] 회원탈퇴 api 
- [x] 소셜로그인 이미지 적용
- [ ] 계정찾기 숫자 허용 로직 적용
- [ ] 사진 업로드 초과 시, 텍스트 적용
- [ ] 멤버이미지
- [ ] 내정보조회 api 호출많이되는문제
